### ISSUE TITLE
[Bug] - Getting Direct Buffer Memory Error on Transformer

### ISSUE THREAD

**Issue by pankajjangid05** [samagra-comms/uci-apis#178]
We need to figure out why it's getting. The error below which we are getting on the production server : 

```
2023-07-14 07:27:13,005 ERROR [reactor-tcp-epoll-7] reactor.util.Loggers$Slf4JLogger:315: Operator called default onErrorDropped
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | reactor.netty.ReactorNetty$InternalNettyException: java.lang.OutOfMemoryError: Direct buffer memory
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | Caused by: java.lang.OutOfMemoryError: Direct buffer memory
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at java.base/java.nio.Bits.reserveMemory(Unknown Source)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:648)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:623)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:202)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.buffer.PoolArena.tcacheAllocateNormal(PoolArena.java:186)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.buffer.PoolArena.allocate(PoolArena.java:136)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:116)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.handler.codec.ByteToMessageDecoder.expandCumulation(ByteToMessageDecoder.java:538)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:97)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:274)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
core_transformer.1.ym4eg272i3vm@UCI-Docker-Swarm-Master    | 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by pankajjangid05** [comment]
Yesterday, we targeted over 112,000 users to trigger notifications. As a result, this error did not occur again. Should we conduct 1 or 2 more tests for Segment 2 before closing it? 

@karntrehan please call on it.

**Comment by chinmoy12c** [comment]
To take a call on this after the next prod trigger.

**Comment by chinmoy12c** [comment]
To be tested on bot trigger today.
